templateVersion: 1.0.0
defaultVersion: v1.8.6
documentation: https://docs.appsmith.com/getting-started/setup/instance-configuration/
type: appsmith
name: Appsmith
description: Fastest way to build internal apps over any database or API.
services:
  $$id:
    image: appsmith/appsmith-ce:$$core_version
    environment:
      - APPSMITH_MAIL_ENABLED=$$config_appsmith_mail_enabled
      - APPSMITH_DISABLE_TELEMETRY=$$config_appsmith_disable_telemetry
      - APPSMITH_DISABLE_INTERCOM=$$config_appsmith_disable_intercom
    volumes:
      - $$id-stacks-data:/appsmith-stacks
    ports:
      - '80'
variables:
  - id: $$config_appsmith_mail_enabled
    name: APPSMITH_MAIL_ENABLED
    label: Enable Mail
    defaultValue: 'false'
    description: ''
  - id: $$config_appsmith_disable_telemetry
    name: APPSMITH_DISABLE_TELEMETRY
    label: Disable Telemetry
    defaultValue: 'true'
    description: ''
  - id: $$config_appsmith_disable_intercom
    name: APPSMITH_DISABLE_INTERCOM
    label: Disable Intercom
    defaultValue: 'true'
    description: ''
