templateVersion: 1.0.0
defaultVersion: '5.22'
documentation: https://docs.ghost.org
type: ghost-mysql
name: Ghost
subname: (MySQL)
description: Ghost is a free and open source blogging platform.
services:
  $$id:
    name: Ghost
    depends_on:
      - $$id-mysql
    image: ghost:$$core_version
    volumes:
      - $$id-ghost:/var/lib/ghost/content
    environment:
      - url=$$config_url
      - database__client=$$config_database__client
      - database__connection__host=$$config_database__connection__host
      - database__connection__user=$$config_mysql_user
      - database__connection__password=$$secret_mysql_password
      - database__connection__database=$$config_mysql_database
    ports:
      - '2368'
  $$id-mysql:
    name: MySQL
    depends_on: []
    image: mysql:8.0
    volumes:
      - $$id-mysql:/var/lib/mysql
    environment:
      - MYSQL_USER=$$config_mysql_user
      - MYSQL_PASSWORD=$$secret_mysql_password
      - MYSQL_DATABASE=$$config_mysql_database
      - MYSQL_ROOT_PASSWORD=$$secret_mysql_root_password
    ports: []
variables:
  - id: $$config_url
    name: url
    label: URL
    defaultValue: $$generate_fqdn
    description: ''
  - id: $$config_database__client
    name: database__client
    label: Database Client
    defaultValue: mysql
    description: ''
    readOnly: true
  - id: $$config_database__connection__host
    name: database__connection__host
    label: Database Host
    defaultValue: $$id-mysql
    description: ''
  - id: $$config_mysql_user
    main: $$id-mysql
    name: MYSQL_USER
    label: MySQL User
    defaultValue: $$generate_username
    description: ''
  - id: $$secret_mysql_password
    main: $$id-mysql
    name: MYSQL_PASSWORD
    label: MySQL Password
    defaultValue: $$generate_password
    description: ''
  - id: $$config_mysql_database
    main: $$id-mysql
    name: MYSQL_DATABASE
    label: MySQL Database
    defaultValue: ghost
    description: ''
  - id: $$secret_mysql_root_password
    name: MYSQL_ROOT_PASSWORD
    label: MySQL Root Password
    defaultValue: $$generate_password
    description: ''
