templateVersion: 1.0.0
defaultVersion: latest
documentation: https://ghost.org/resources/
type: ghost-mariadb
name: Ghost
subname: (MariaDB)
description: Free and open source blogging platform.
labels:
  - cms
  - blog
services:
  $$id:
    name: Ghost
    documentation: Taken from https://docs.ghost.org/
    depends_on:
      - $$id-mariadb
    image: bitnami/ghost:$$core_version
    volumes:
      - $$id-ghost:/bitnami/ghost
    environment:
      - url=$$config_url
      - GHOST_HOST=$$config_ghost_host
      - GHOST_ENABLE_HTTPS=$$config_ghost_enable_https
      - GHOST_EMAIL=$$config_ghost_email
      - GHOST_PASSWORD=$$secret_ghost_password
      - GHOST_DATABASE_HOST=$$config_ghost_database_host
      - GHOST_DATABASE_USER=$$config_mariadb_user
      - GHOST_DATABASE_PASSWORD=$$secret_ghost_database_password
      - GHOST_DATABASE_NAME=$$config_mariadb_database
      - GHOST_DATABASE_PORT_NUMBER=3306
    ports:
      - '2368'
  $$id-mariadb:
    name: MariaDB
    depends_on: []
    image: bitnami/mariadb:latest
    volumes:
      - $$id-mariadb:/bitnami/mariadb
    environment:
      - MARIADB_USER=$$config_mariadb_user
      - MARIADB_PASSWORD=$$secret_mariadb_password
      - MARIADB_DATABASE=$$config_mariadb_database
      - MARIADB_ROOT_USER=$$config_mariadb_root_user
      - MARIADB_ROOT_PASSWORD=$$secret_mariadb_root_password
    ports: []
variables:
  - id: $$config_url
    name: url
    label: URL
    defaultValue: $$generate_fqdn
    description: ''
  - id: $$config_ghost_host
    name: GHOST_HOST
    label: Ghost Host
    defaultValue: $$generate_domain
    description: ''
  - id: $$config_ghost_enable_https
    name: GHOST_ENABLE_HTTPS
    label: Ghost Enable HTTPS
    defaultValue: 'no'
    description: ''
  - id: $$config_ghost_email
    name: GHOST_EMAIL
    label: Ghost Default Email
    defaultValue: admin@example.com
    description: ''
  - id: $$secret_ghost_password
    name: GHOST_PASSWORD
    label: Ghost Default Password
    defaultValue: $$generate_password
    description: ''
    showOnConfiguration: true
  - id: $$config_ghost_database_host
    name: GHOST_DATABASE_HOST
    label: Ghost Database Host
    defaultValue: $$id-mariadb
    description: ''
  - id: $$config_ghost_database_user
    name: GHOST_DATABASE_USER
    label: MariaDB User
    defaultValue: $$config_mariadb_user
    description: ''
  - id: $$secret_ghost_database_password
    name: GHOST_DATABASE_PASSWORD
    label: MariaDB Password
    defaultValue: $$secret_mariadb_password
    description: ''
  - id: $$config_ghost_database_name
    name: GHOST_DATABASE_NAME
    label: MariaDB Database
    defaultValue: $$config_mariadb_database
    description: ''
  - id: $$config_mariadb_user
    name: MARIADB_USER
    label: MariaDB User
    defaultValue: $$generate_username
    description: ''
  - id: $$secret_mariadb_password
    name: MARIADB_PASSWORD
    label: MariaDB Password
    defaultValue: $$generate_password
    description: ''
  - id: $$config_mariadb_database
    name: MARIADB_DATABASE
    label: MariaDB Database
    defaultValue: ghost
    description: ''
  - id: $$config_mariadb_root_user
    name: MARIADB_ROOT_USER
    label: MariaDB Root User
    defaultValue: $$generate_username
    description: ''
  - id: $$secret_mariadb_root_password
    name: MARIADB_ROOT_PASSWORD
    label: MariaDB Root Password
    defaultValue: $$generate_password
    description: ''
