templateVersion: 1.0.0
defaultVersion: v2.0.6
documentation: https://glitchtip.com/documentation
type: glitchtip
name: GlitchTip
description: ''
services:
  $$id:
    name: GlitchTip
    depends_on:
      - $$id-postgresql
      - $$id-redis
    image: glitchtip/glitchtip:$$core_version
    volumes: []
    environment:
      - PORT=$$config_port
      - GLITCHTIP_DOMAIN=$$config_glitchtip_domain
      - SECRET_KEY=$$secret_secret_key
      - DATABASE_URL=$$secret_database_url
      - REDIS_URL=$$secret_redis_url
      - DEFAULT_FROM_EMAIL=$$config_default_from_email
      - EMAIL_URL=$$secret_email_url
      - EMAIL_HOST=$$config_email_host
      - EMAIL_PORT=$$config_email_port
      - EMAIL_HOST_USER=$$config_email_host_user
      - EMAIL_HOST_PASSWORD=$$secret_email_host_password
      - EMAIL_USE_TLS=$$config_email_use_tls
      - EMAIL_USE_SSL=$$config_email_use_ssl
      - EMAIL_BACKEND=$$config_email_backend
      - MAILGUN_API_KEY=$$secret_mailgun_api_key
      - SENDGRID_API_KEY=$$secret_sendgrid_api_key
      - ENABLE_OPEN_USER_REGISTRATION=$$config_enable_open_user_registration
      - DJANGO_SUPERUSER_EMAIL=$$config_django_superuser_email
      - DJANGO_SUPERUSER_PASSWORD=$$secret_django_superuser_password
      - DJANGO_SUPERUSER_USERNAME=$$config_django_superuser_username
      - CELERY_WORKER_CONCURRENCY=$$config_celery_worker_concurrency
    ports:
      - '8000'
  $$id-worker:
    name: Celery Worker
    command: ./bin/run-celery-with-beat.sh
    depends_on:
      - $$id-postgresql
      - $$id-redis
    image: glitchtip/glitchtip:$$core_version
    environment:
      - GLITCHTIP_DOMAIN=$$config_glitchtip_domain
      - SECRET_KEY=$$secret_secret_key
      - DATABASE_URL=$$secret_database_url
      - REDIS_URL=$$secret_redis_url
      - DEFAULT_FROM_EMAIL=$$config_default_from_email
      - EMAIL_URL=$$secret_email_url
      - CELERY_WORKER_CONCURRENCY=$$config_celery_worker_concurrency
    ports: []
  $$id-migrate:
    exclude: true
    name: Migrate
    command: ./manage.py migrate
    depends_on:
      - $$id-postgresql
      - $$id-redis
    image: glitchtip/glitchtip:$$core_version
    environment:
      - GLITCHTIP_DOMAIN=$$config_glitchtip_domain
      - SECRET_KEY=$$secret_secret_key
      - DATABASE_URL=$$secret_database_url
      - REDIS_URL=$$secret_redis_url
      - DEFAULT_FROM_EMAIL=$$config_default_from_email
      - EMAIL_URL=$$secret_email_url
    ports: []
  $$id-postgresql:
    name: PostgreSQL
    depends_on: []
    image: postgres:14-alpine
    volumes:
      - $$id-postgresql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$$config_postgres_user
      - POSTGRES_PASSWORD=$$secret_postgres_password
      - POSTGRES_DB=$$config_postgres_db
    ports: []
  $$id-redis:
    name: Redis
    depends_on: []
    image: redis:7-alpine
    volumes:
      - $$id-postgresql-redis-data:/data
    environment: []
    ports: []
variables:
  - id: $$config_django_superuser_username
    name: DJANGO_SUPERUSER_USERNAME
    label: Django Superuser Username
    defaultValue: $$generate_username
    description: ''
  - id: $$secret_django_superuser_password
    name: DJANGO_SUPERUSER_PASSWORD
    label: Django Superuser Password
    defaultValue: $$generate_password
    description: ''
    showOnConfiguration: true
  - id: $$config_port
    name: PORT
    label: GlitchTip Port
    defaultValue: '8000'
    description: ''
  - id: $$config_celery_worker_concurrency
    main: $$id-worker
    name: CELERY_WORKER_CONCURRENCY
    label: Celery Worker Concurrency
    defaultValue: '2'
    description: ''
  - id: $$config_glitchtip_domain
    name: GLITCHTIP_DOMAIN
    label: GlitchTip Domain
    defaultValue: $$generate_fqdn
    description: ''
  - id: $$secret_email_url
    name: EMAIL_URL
    label: SMTP Email URL
    defaultValue: >-
      smtp://$$config_email_host_user:$$secret_email_host_password@$$config_email_host:$$config_email_port
    description: ''
  - id: $$secret_database_url
    name: DATABASE_URL
    label: Database URL for PostgreSQL
    defaultValue: >-
      postgresql://$$config_postgres_user:$$secret_postgres_password@$$id-postgresql:5432/$$config_postgres_db
    description: ''
  - id: $$secret_redis_url
    name: REDIS_URL
    label: Redis URL
    defaultValue: redis://$$id-redis:6379/0
    description: ''
  - id: $$config_default_from_email
    name: DEFAULT_FROM_EMAIL
    label: Default Email Address
    defaultValue: noreply@example.com
    description: ''
  - id: $$config_email_host
    name: EMAIL_HOST
    label: Email SMTP Host
    defaultValue: ''
    description: ''
  - id: $$config_email_port
    name: EMAIL_PORT
    label: Email SMTP Port
    defaultValue: '25'
    description: ''
  - id: $$config_email_host_user
    name: EMAIL_HOST_USER
    label: Email SMTP User
    defaultValue: ''
    description: ''
  - id: $$secret_email_host_password
    name: EMAIL_HOST_PASSWORD
    label: Email SMTP Password
    defaultValue: ''
    description: ''
  - id: $$config_email_use_tls
    name: EMAIL_USE_TLS
    label: Email Use TLS
    defaultValue: 'false'
    description: ''
  - id: $$config_email_use_ssl
    name: EMAIL_USE_SSL
    label: Email Use SSL
    defaultValue: 'false'
    description: ''
  - id: $$secret_email_smtp_password
    name: EMAIL_SMTP_PASSWORD
    label: SMTP Password
    defaultValue: ''
    description: ''
  - id: $$config_email_backend
    name: EMAIL_BACKEND
    label: Email Backend
    defaultValue: ''
    description: ''
  - id: $$secret_mailgun_api_key
    name: MAILGUN_API_KEY
    label: Mailgun API Key
    defaultValue: ''
    description: ''
    showOnConfiguration: true
  - id: $$secret_sendgrid_api_key
    name: SENDGRID_API_KEY
    label: Sendgrid API Key
    defaultValue: ''
    description: ''
    showOnConfiguration: true
  - id: $$config_enable_open_user_registration
    name: ENABLE_OPEN_USER_REGISTRATION
    label: Enable Open User Registration
    defaultValue: 'true'
    description: ''
  - id: $$config_django_superuser_email
    name: DJANGO_SUPERUSER_EMAIL
    label: Django Superuser Email
    defaultValue: noreply@example.com
    description: ''
  - id: $$config_postgres_user
    main: $$id-postgresql
    name: POSTGRES_USER
    label: PostgreSQL User
    defaultValue: $$generate_username
    description: ''
  - id: $$secret_postgres_password
    main: $$id-postgresql
    name: POSTGRES_PASSWORD
    label: PostgreSQL Password
    defaultValue: $$generate_password
    description: ''
  - id: $$config_postgres_db
    main: $$id-postgresql
    name: POSTGRES_DB
    label: PostgreSQL Database
    defaultValue: glitchtip
    description: ''
