templateVersion: 1.0.0
defaultVersion: v0.29.1
documentation: https://docs.meilisearch.com/learn/getting_started/quick_start.html
type: meilisearch
name: MeiliSearch
description: >-
  MeiliSearch is a lightning Fast, Ultra Relevant, and Typo-Tolerant Search
  Engine
services:
  $$id:
    name: MeiliSearch
    documentation: https://docs.meilisearch.com/
    depends_on: []
    image: getmeili/meilisearch:$$core_version
    volumes:
      - $$id-datams:/meili_data/data.ms
      - $$id-data:/meili_data
      - $$id-snapshot:/snapshot
      - $$id-dump:/dumps
    environment:
      - MEILI_MASTER_KEY=$$secret_meili_master_key
    ports:
      - '7700'
variables:
  - id: $$secret_meili_master_key
    name: MEILI_MASTER_KEY
    label: Master Key
    defaultValue: $$generate_hex(64)
    description: ''
    showOnConfiguration: true
