templateVersion: 1.0.0
defaultVersion: 4.7.1
documentation: https://coder.com/docs/coder-oss/latest
type: vscodeserver
name: VSCode Server
description: Visual Studio Code on a remote server, accessible through the browser.
labels:
  - vscode
  - ide
services:
  $$id:
    name: VSCode Server
    depends_on: []
    image: codercom/code-server:$$core_version
    volumes:
      - $$id-config-data:/home/coder/.local/share/code-server
      - $$id-vscodeserver-data:/home/coder
      - $$id-keys-directory:/root/.ssh
      - $$id-theme-and-plugin-directory:/root/.local/share/code-server
    environment:
      - PASSWORD=$$secret_password
    ports:
      - '8080'
variables:
  - id: $$secret_password
    name: PASSWORD
    label: Password
    defaultValue: $$generate_password
    description: ''
    showOnConfiguration: true
